get: # Http Get ===========================================
  "":
    controller: home
    method: index
    namespace: Client/brand
  home:
    controller: home
    method: index
    namespace: Client/brand
  todo:
    controller: home
    method: todo
    namespace: Client/components
  checkout:
    controller: home
    method: index
    namespace: Client
  lib:
    controller: home
    method: lib
    namespace: Client/brand/clothes
  learn:
    controller: learning
    method: index
    namespace: Client
  admin/{controller}/{method}:
    namespace: Admin
  admin/{controller}/{method}/{id:[\da-f]+}:
    namespace: Admin
  client/{controller}/{method}:
    namespace: Client
  /{controller}/{method}:
    namespace: Client
  /{controller}/{method}/{id:[\da-f]+}:
    namespace: Client
  client/{controller}/{method}/{id:[\da-f]+}:
    namespace: Client

post: # Http Post method =========================================================
  visitors:
    controller: visitors
    method: track
  ajaxLogin:
    controller: login_user_with_ajax
    method: index
  ajaxlogout:
    controller: logout_user_with_ajax
    method: index
  ajaxRegister:
    controller: register_user_with_ajax
    method: index
  forgotPassword:
    controller: forgot_password_ajax
    method: index
  verify:
    controller: user_account
    method: verify
  remember_me:
    controller: login_user_with_ajax
    method: rememberMeCheck
  comments:
    controller: comments
    method: newComment
  get_countries:
    controller: country
    method: getCountries
  add_item_into_cart:
    controller: user_cart
    method: add
  activation/activate/{token:[\da-f]+}:
    controller: activate_user_with_ajax
    method: activate
